"""baseline schema from declarative metadata

Creates the entire current schema from SQLAlchemy ``Base.metadata``. This is the
baseline migration for an app that previously bootstrapped via ``create_all`` +
ad-hoc ALTERs. For an existing database that already has these tables, run
``alembic stamp 0001_baseline`` instead of upgrading. Future schema changes must
be authored as new autogenerated migrations.

Revision ID: 0001_baseline
Revises:
Create Date: 2025-06-04
"""
from typing import Sequence, Union

from alembic import op

import app.models  # noqa: F401 — register every model on Base.metadata
from app.models.base import Base

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
